version: "3.9"

services:
  sandbox:
    build:
      context: docker/sandbox
      dockerfile: Dockerfile
    image: platform-ide-python-sandbox:latest
    command: ["sleep", "infinity"]
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: platform-ide-api:latest
    environment:
      SANDBOX_IMAGE: platform-ide-python-sandbox:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/app/config.json:ro
      - ./output:/app/output
    depends_on:
      - sandbox
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ""
    image: platform-ide-web:latest
    environment:
      NEXT_PUBLIC_BACKEND_URL: ""
      OPENAI_API_KEY: "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"
      OPENAI_MODEL: "gpt-5-mini"
      GEMINI_API_KEY: "AIzaSyCUP24fUjQa5URokX1viGqJOB03uN-SlD4"
      GEMINI_MODEL: "gemini-2.5-flash"
      DEEPSEEK_API_KEY: "sk-8102e40a3ccb42b9a40ea6ab8467530b"
      DEEPSEEK_MODEL: "deepseek-chat"
    depends_on:
      - api
    restart: unless-stopped

  nginx:
    image: nginx:stable
    depends_on:
      - web
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
